name: Build and Deploy Frontend

on:
  push:
    paths:
      - "react/**" # react 폴더 내의 파일이 변경될 때만 실행

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v2

      - name: Docker Buildx 설정
        uses: docker/setup-buildx-action@v1

      - name: Docker Hub 로그인
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker image 빌드 & 푸쉬
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/jm-total-hub:react-latest

      - name: react 폴더 생성(있으면 무시)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REACT_SERVER01_EC2_HOST }}
          username: ${{ secrets.REACT_SERVER01_EC2_USERNAME }}
          key: ${{ secrets.REACT_SERVER01_EC2_PRIVATE_KEY }}
          script: |
            mkdir -p ~/react

      - name: react폴더내용 ec2서버 react폴더에 업로드 (최신화)
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REACT_SERVER01_EC2_HOST }}
          username: ${{ secrets.REACT_SERVER01_EC2_USERNAME }}
          key: ${{ secrets.REACT_SERVER01_EC2_PRIVATE_KEY }}
          source: "react/*"
          target: "~/react/"

      - name: EC2 배포
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REACT_SERVER01_EC2_HOST }}
          username: ${{ secrets.REACT_SERVER01_EC2_USERNAME }}
          key: ${{ secrets.REACT_SERVER01_EC2_PRIVATE_KEY }}
          script: |
            docker image prune -a -f --filter "until=12h"
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            export REACT_ENV_STATUS=${{ secrets.REACT_ENV_STATUS }}
            export EXPRESS_SERVER01_EC2_HOST=${{ secrets.EXPRESS_SERVER01_EC2_HOST }}
            cd JMTotalHub-DockerCompose
            sudo -E docker-compose pull react 
            sudo -E docker-compose up -d react
