version: "3.9"
services:
  react:
    image: junmop950/jm-total-hub:react-latest
    ports:
      - "3000:3000"
    environment:
      REACT_APP_ENV_STATUS: ${REACT_APP_ENV_STATUS}
      REACT_APP_NGINX_SERVER_HOST: ${REACT_APP_NGINX_SERVER_HOST}
      REACT_APP_EXPRESS_SERVER01_HOST: ${REACT_APP_EXPRESS_SERVER01_HOST}
