name: Epxress 백엔드 서버 배포

on:
  push:
    paths:
      - "express/**" # express 폴더 내의 파일이 변경될 때만 실행

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v2

      - name: express 폴더 생성(있으면 무시)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EXPRESS_SERVER01_EC2_HOST }}
          username: ${{ secrets.EXPRESS_SERVER01_EC2_USERNAME }}
          key: |
            ${{ secrets.EXPRESS_SERVER01_EC2_PRIVATE_KEY }}
          script: |
            mkdir -p ~/express

      - name: express폴더내용 ec2서버 express폴더에 업로드 (최신화)
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EXPRESS_SERVER01_EC2_HOST }}
          username: ${{ secrets.EXPRESS_SERVER01_EC2_USERNAME }}
          key: |
            ${{ secrets.EXPRESS_SERVER01_EC2_PRIVATE_KEY }}
          source: "express/*"
          target: "~/express/"
